apiVersion: apps/v1
kind: Deployment
metadata: 
    name: homebot-bl-deployment
spec:
    selector:
        matchLabels:
            app: homebotBLApp
    replicas: 1
    template:
        metadata:
            labels:
                app: homebotBLApp
        spec:
            containers:
                -   name: homebot-bl-container
                    image: laurencelungo/homebot-bl
                    ports:
                        -   containerPort: 8000
            imagePullSecrets:
                - name: regcred
    selector:
        matchLabels:
            app: homebotBLApp
