apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: homebot-bl
  name: homebot-bl
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: homebot-bl
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: homebot-bl
    spec:
      containers:
      - image: laurencelungo/homebot-bl:arm32v7
        imagePullPolicy: ""
        name: homebot-bl
        ports:
        - containerPort: 8000
        resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
