apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - image: redis
        imagePullPolicy: ""
        name: cache
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert
      kompose.version: 1.21.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: redis
    name: redis
  spec:
    ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
    selector:
      io.kompose.service: redis
  status:
    loadBalancer: {}
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert
      kompose.version: 1.21.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: homebot-bl
    name: homebot-bl
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: homebot-bl
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: kompose convert
          kompose.version: 1.21.0 ()
        creationTimestamp: null
        labels:
          io.kompose.service: homebot-bl
      spec:
        containers:
        - image: laurencelungo/homebot-bl:latest
          imagePullPolicy: ""
          name: homebot-bl
          ports:
          - containerPort: 8000
          resources: {}
        imagePullSecrets:
        - name: regcred
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
---
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert
      kompose.version: 1.21.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: homebot-bl
    name: homebot-bl
  spec:
    type: NodePort
    ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      nodePort: 30000
    selector:
      io.kompose.service: homebot-bl
  status:
    loadBalancer: {}
  