apiVersion: v1
kind: Pod
metadata:
  name: homebot-bl-pod
  labels:
    app: homebotBLApp
spec:
  containers:
    - name: homebot-bl-container
      image: laurencelungo/homebot-bl
      ports:
        - containerPort: 8000
  imagePullSecrets:
    - name: regcred
