apiVersion: v1
kind: Service
metadata:
    labels:
        io.kompose.service: redis
    name: redis
spec:
    selector:
        io.kompose.service: redis
    ports:
      - protocol: TCP
        port: 6379 # [in node] service's <cluster IP: port> => access API
        targetPort: 6379 # port in container k8s should look for 
        # nodePort: 30000 # [in networok] node's <internal IP: port> => access API
